---
version: "3"

services:
  web:
    image: httpd:latest
    ports:
      - "80"

    volumes:
      - .:/var/www/html
  
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./mysqlVol:/var/lib/mysql
