---
version: '3'
services:
  web:
    image: alicek106/composetest:web
    ports:
      - "80:80"
    links:
      - mysql:mysql
    command: apachectl -DFOREGROUND
 
  mysql:
    image: alicek106/composetest:mysql
    command: mysqld
    
